name: "DDEV add-on test"
author: "Julien Loizelet"
description: "A Github Action to run DDEV add-on tests"

inputs:

  ddev_version:
    type: choice
    required: true
    default: "stable"
    description: "DDEV Version to use"
    options:
      - "stable"
      - "HEAD"
  debug_enabled:
    type: boolean
    description: Debug with tmate
    required: false
    default: false
  token:
    description: 'A Github PAT'
    required: true

runs:
  using: "composite"
  steps:

    - uses: Homebrew/actions/setup-homebrew@master

    - name: Environment setup
      shell: bash
      run: |
        brew install bats-core mkcert
        mkcert -install

    - name: Use ddev stable
      shell: bash
      if: inputs.ddev_version == 'stable'
      run: brew install ddev/ddev/ddev

    - name: Use ddev HEAD
      shell: bash
      if: inputs.ddev_version == 'HEAD'
      run: brew install --HEAD ddev/ddev/ddev

    - name: Download docker images
      shell: bash
      run: ddev debug download-images >/dev/null

    - uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true
        github-token: ${{ inputs.token }}
      if: inputs.debug_enabled == 'true'

    - name: Run test
      shell: bash
      run: bats tests

    - uses: gautamkrishnar/keepalive-workflow@v1
      # keepalive-workflow adds a dummy commit if there's no other action here, keeps
      # GitHub from turning off tests after 60 days
      with:
        commit_message: "chore(*): Automated commit to keep the repository active"
        time_elapsed: 1
      if: inputs.ddev_version == 'stable'

branding:
  icon: "code"
  color: "green"
