name: "DDEV add-on test"
author: "Julien Loizelet"
description: "A Github Action to run DDEV add-on tests"

inputs:

  ddev_version:
    type: choice
    required: true
    default: "stable"
    description: "DDEV Version to use"
    options:
      - "stable"
      - "HEAD"
      -
  debug_enabled:
    type: boolean
    description: Debug with tmate
    required: false
    default: false

  token:
    description: 'A Github PAT'
    required: true

runs:
  using: "composite"
  steps:

    - uses: Homebrew/actions/setup-homebrew@master

    - name: Environment setup
      shell: bash
      run: |
        brew install bats-core mkcert
        mkcert -install

    - name: Use ddev stable
      shell: bash
      if: inputs.ddev_version == 'stable'
      run: brew install ddev/ddev/ddev

    - name: Use ddev HEAD
      shell: bash
      if: inputs.ddev_version == 'HEAD'
      run: brew install --HEAD ddev/ddev/ddev

    - name: Download docker images
      shell: bash
      run: ddev debug download-images >/dev/null

    - uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true
        github-token: ${{ inputs.token }}
      if: inputs.debug_enabled == 'true'

    - name: Run test
      # Allow ddev get to use a GitHub token to prevent rate limiting by tests
      env:
        DDEV_GITHUB_TOKEN: ${{ inputs.token }}
      shell: bash
      run: bats tests

branding:
  icon: "code"
  color: "green"
