name: Add-on with disabled checkout tests
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  schedule:
    - cron: '25 08 * * *'
  workflow_dispatch:

permissions:
  contents: write


jobs:
  add-on-disable-checkout-test:
    strategy:
      fail-fast: false
      matrix:
        ddev_version: [ stable ]
        add_on: ["JanoPL/ddev-kibana"]

    name: Add-on with disabled checkout tests
    runs-on: ubuntu-latest

    steps:

      - name: Clone current repository
        uses: actions/checkout@v3

      - name: Retrieve last tag of add-on
        run: |
          echo "ADD_ON_LAST_TAG=$(curl -Ls -o /dev/null -w %{url_effective} https://github.com/${{ matrix.add_on }}/releases/latest | grep -oP "\/tag\/\K(.*)$")" >> $GITHUB_ENV 

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ matrix.add_on }}
          ref: ${{ env.ADD_ON_LAST_TAG }}
          path: tested-addon
          submodules: 'true'

      - name: Run DDEV test (${{ matrix.ddev_version }})
        uses: ./
        with:
          ddev_version: ${{ matrix.ddev_version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          addon_repository: ${{ matrix.add_on }}
          addon_ref: ${{ env.ADD_ON_LAST_TAG }}
          addon_path: tested-addon
          keepalive: false
          disable_checkout_action: true

