name: Add-on simple tests
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  schedule:
    - cron: '25 08 * * *'
  workflow_dispatch:

permissions:
  contents: write


jobs:
  add-on-simple-test:
    strategy:
      fail-fast: false
      matrix:
        ddev_version: [ stable, HEAD ]

    name: Add-on simple tests
    runs-on: ubuntu-20.04
    env:
      ADDON_GITHUB_URL: "julienloizelet/ddev-playwright"

    steps:

      - name: Clone current repository
        uses: actions/checkout@v3

      - name: Run DDEV test (${{ matrix.ddev_version }})
        uses: ./
        with:
          ddev_version: ${{ matrix.ddev_version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          addon_repository: ${{ env.ADDON_GITHUB_URL }}
          addon_ref: v2.1.1
          addon_path: tested-addon
          keepalive: false
