name: Disable checkout test
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  schedule:
    - cron: '25 08 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  disable-checkout-test:
    strategy:
      fail-fast: false
      matrix:
        ddev_version: [ stable ]
        add_on: ["JanoPL/ddev-kibana"]

    name: Disable checkout test
    runs-on: ubuntu-latest

    env:
      ADD_ON: JanoPL/ddev-kibana
      ADD_ON_REF: v1.4.0

    steps:

      - name: Clone current repository
        uses: actions/checkout@v3

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ env.ADD_ON }}
          ref: ${{ env.ADD_ON_REF }}
          path: tested-addon
          submodules: 'true'

      - name: Run DDEV test (${{ matrix.ddev_version }})
        uses: ./
        with:
          ddev_version: ${{ matrix.ddev_version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          addon_repository: ${{ env.ADD_ON }}
          addon_ref: ${{ env.ADD_ON_REF }}
          addon_path: tested-addon
          keepalive: false
          disable_checkout_action: true

